"""Auditable agent infrastructure for company-intelligence analysis."""

from market_checker_app.agents.contracts import (
    ActivationState,
    AgentContext,
    AgentEvidence,
    AgentExecution,
    AgentResult,
    AgentSignal,
    AgentStatus,
    ClaimStatus,
    CompanyRelationship,
    DecisionRecord,
    DocumentRecord,
    DocumentSourceResolution,
    DocumentSourcePriority,
    EntityRecord,
    FundamentalFact,
    FundamentalFeatureSnapshot,
    GateDecision,
    GovernanceEvent,
    GovernanceEventStatus,
    GovernanceEventType,
    IdentityConflictRecord,
    IdentityConflictStatus,
    OrchestrationReport,
    PolicyEvaluation,
    QualityGateCheck,
    RegulatoryContractEvent,
    RegulatoryContractEventType,
    RegulatoryEventStatus,
    RelationshipType,
    ResearchClaim,
    ResourceExposure,
    ResourceExposureType,
    SignalActivationDecision,
)
from importlib import import_module

_AGENT_MODULES = {
    "ClaimVerificationAgent": "claim_verification_agent",
    "CommodityEnergyAgent": "commodity_energy_agent",
    "DecisionAgent": "decision_agent",
    "EntityRegistryAgent": "entity_registry_agent",
    "EuropeanFilingsAgent": "european_filings_agent",
    "EvaluationAgent": "evaluation_agent",
    "FinancialForensicsAgent": "financial_forensics_agent",
    "GovernanceEventAgent": "governance_event_agent",
    "OrchestratorAgent": "orchestrator",
    "PredictionV21AdapterAgent": "prediction_v21_adapter",
    "QualityGateAgent": "quality_gate_agent",
    "RegulatoryContractAgent": "regulatory_contract_agent",
    "SecFundamentalsAgent": "sec_fundamentals_agent",
    "ShortReportAgent": "short_report_agent",
    "SourceResolutionAgent": "source_resolution_agent",
    "SupplyChainAgent": "supply_chain_agent",
}


def __getattr__(name: str):
    # Importing a data contract must not recursively initialize every agent
    # and its services. Preserve package-level imports without import cycles.
    if name not in _AGENT_MODULES:
        raise AttributeError(name)
    value = getattr(import_module(f"{__name__}.{_AGENT_MODULES[name]}"), name)
    globals()[name] = value
    return value

__all__ = [
    "ActivationState",
    "AgentContext",
    "AgentEvidence",
    "AgentExecution",
    "AgentResult",
    "AgentSignal",
    "AgentStatus",
    "ClaimStatus",
    "ClaimVerificationAgent",
    "CommodityEnergyAgent",
    "CompanyRelationship",
    "DecisionAgent",
    "DecisionRecord",
    "DocumentRecord",
    "DocumentSourceResolution",
    "DocumentSourcePriority",
    "EntityRecord",
    "EntityRegistryAgent",
    "EuropeanFilingsAgent",
    "EvaluationAgent",
    "FinancialForensicsAgent",
    "FundamentalFact",
    "FundamentalFeatureSnapshot",
    "GateDecision",
    "GovernanceEventAgent",
    "GovernanceEvent",
    "GovernanceEventStatus",
    "GovernanceEventType",
    "IdentityConflictRecord",
    "IdentityConflictStatus",
    "OrchestrationReport",
    "OrchestratorAgent",
    "PredictionV21AdapterAgent",
    "PolicyEvaluation",
    "QualityGateAgent",
    "QualityGateCheck",
    "RegulatoryContractAgent",
    "RegulatoryContractEvent",
    "RegulatoryContractEventType",
    "RegulatoryEventStatus",
    "RelationshipType",
    "ResearchClaim",
    "ResourceExposure",
    "ResourceExposureType",
    "SecFundamentalsAgent",
    "ShortReportAgent",
    "SourceResolutionAgent",
    "SignalActivationDecision",
    "SupplyChainAgent",
]
